version: '3.8'

services:
  db:
    container_name: hrm_db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Abcd@1234"
    ports:
      - "1433:1433"
    restart: always
    volumes:
      - hrmsql:/var/opt/mssql
  api:
    container_name: hrm_api
    image: drglasdou/hrm-api:2024_01_23
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db;Initial Catalog=hrm;User Id=sa;Password=Abcd@1234;Trust Server Certificate=true;MultipleActiveResultSets=true;
    restart: always

volumes:
  hrmsql:
