// Generated by https://quicktype.io

export interface Employee {
  name: string;
  code: string;
  email: string;
  phone: string;
  salary: number;
  id: number;
  createdAt: Date | string;
  updatedAt: null | Date | string;
  deletedAt: null | Date | string;
}
