name: Create and Push Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ closed ]

jobs:
  build:
    name: Building image
    runs-on: ubuntu-latest

    # This condition ensures that the job runs on push to main or if the pull request is merged (closed)
    if: |
      github.event_name == 'push' ||
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
        
    steps:    
      - name: Check out the repo
        uses: actions/checkout@v2
        
      - name: Set the Docker image name as an environment variable
        run: echo "DOCKER_IMAGE_NAME=hrm-app" >> $GITHUB_ENV

      - name: Generate date tag
        id: date_tag
        run: echo "DATE_TAG=$(date +'%Y_%m_%d')" >> $GITHUB_ENV
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./HRM.WebAPI/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DATE_TAG }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest         
